---
title: "Workshop: Data Visualization & Statistics in R"
subtitle: "Ecology & Evolution: Senior Seminar"
author: "TS O'Leary"
date: "2025-02-11"
description: "Spring 2025: Workshop in R for a seminar course at UVM."
output:
  bookdown::gitbook:
    number_sections: true
    split_by: chapter
    toc_depth: 4
    toc_collapse: true
documentclass: book
---

<!-- A quick note to myself about compiling the gitbook. Render this book by using the Knit button in RStudio. When updating the book and knitting again, it may be useful to remove all directories and previous files other than this index.Rmd file. That will avoid saving old files whose sections have been re-named and therefore no longer exist, etc.  -->

```{r, setup, include = FALSE}
knitr::opts_knit$set(root.dir = here::here())
```

# Workshop overview {-}

## Step 0: Download R & RStudio  {-}

1. 
2. 

## Agenda {-}

### Day One {-}

-
-
-
-

### Day Two {-}

-
-
-
-


## Links {-}







# Day One

```{r, file = "src/01_day.R"}
```

# Day Two

```{r, file = "src/02_day.R"}
```


# Session Info {-}

```{r}
sessionInfo()
```